"""
Notebook 03 — Exploratory Data Analysis
Standalone EDA script. All plots also generated by run_pipeline.py.
"""
import os, sys
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
if BASE_DIR.endswith("notebooks"):
    BASE_DIR = os.path.dirname(BASE_DIR)

PROC_DIR = os.path.join(BASE_DIR, "data", "processed")
FIG_DIR  = os.path.join(BASE_DIR, "outputs", "figures")
os.makedirs(FIG_DIR, exist_ok=True)

PALETTE = ["#1A3C5E","#2E86AB","#A23B72","#F18F01","#C73E1D",
           "#3B1F2B","#44BBA4","#E94F37","#393E41","#F5A623"]
sns.set_theme(style="whitegrid", palette=PALETTE, font_scale=1.1)

print("Loading data …")
txn     = pd.read_csv(os.path.join(PROC_DIR, "transactions_clean.csv"), parse_dates=["txn_date"])
cust    = pd.read_csv(os.path.join(PROC_DIR, "customer_summary.csv"))
monthly = pd.read_csv(os.path.join(PROC_DIR, "monthly_trends.csv"))
cat_sum = pd.read_csv(os.path.join(PROC_DIR, "category_summary.csv"))

print(f"Transactions : {len(txn):,}")
print(f"Customers    : {len(cust):,}")

# ── Summary Statistics ─────────────────────────────────────────────────────────
print("\n── Transactions Summary ──")
print(txn[["amount","cashback_amt","interchange_revenue"]].describe().round(2))

print("\n── Spend by Category (Top 5) ──")
print(cat_sum.nlargest(5, "total_spend")[["category","total_spend","total_cashback"]].to_string(index=False))

print("\n── Spend by Channel ──")
print(txn.groupby("channel")["amount"].sum().sort_values(ascending=False).apply(lambda x: f"₹{x/1e6:.2f}M"))

print("\n── Cashback Cost by Card Type ──")
print(txn.groupby("card_type")["cashback_amt"].sum().sort_values(ascending=False).apply(lambda x: f"₹{x/1e6:.2f}M"))

print("\n── Monthly Spend (Jan 2023 – Dec 2024) ──")
print(monthly[["year_month","total_spend","total_cashback","net_revenue"]].to_string(index=False))

print("\nEDA complete — all plots generated in outputs/figures/")
